name: 'License Compliance'

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 6 * * 1'  # Weekly check on Mondays

jobs:
  license-check:
    name: License Compliance Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci

    - name: Install license checker
      run: |
        npm install -g license-checker

    - name: Run license compliance check
      run: |
        license-checker --json > security-reports/license-report.json
        license-checker --summary > security-reports/license-summary.txt
        license-checker --csv > security-reports/license-report.csv

    - name: Check for prohibited licenses
      run: |
        # Check for common prohibited licenses
        PROHIBITED_LICENSES=("GPL" "LGPL" "AGPL" "CC-BY-SA" "CC-BY-NC")

        echo "Checking for prohibited licenses..."
        FOUND_PROHIBITED=false

        for license in "${PROHIBITED_LICENSES[@]}"; do
          if grep -i "$license" security-reports/license-summary.txt > /dev/null; then
            echo "⚠️  Found potentially prohibited license: $license"
            FOUND_PROHIBITED=true
          fi
        done

        if [ "$FOUND_PROHIBITED" = true ]; then
          echo "❌ Prohibited licenses found! Please review dependencies."
          exit 1
        else
          echo "✅ No prohibited licenses found."
        fi

    - name: Generate license report
      run: |
        echo "# License Compliance Report" > security-reports/license-report.md
        echo "" >> security-reports/license-report.md
        echo "## Generated: $(date)" >> security-reports/license-report.md
        echo "" >> security-reports/license-report.md
        echo "## License Summary" >> security-reports/license-report.md
        echo "\`\`\`" >> security-reports/license-report.md
        cat security-reports/license-summary.txt >> security-reports/license-report.md
        echo "\`\`\`" >> security-reports/license-report.md
        echo "" >> security-reports/license-report.md
        echo "## Detailed License Information" >> security-reports/license-report.md
        echo "See license-report.json and license-report.csv for detailed information." >> security-reports/license-report.md

    - name: Comment PR with license info
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');

          let comment = '## 📄 License Compliance Check\n\n';

          if (fs.existsSync('security-reports/license-summary.txt')) {
            const licenseSummary = fs.readFileSync('security-reports/license-summary.txt', 'utf8');
            comment += '```\n' + licenseSummary + '\n```\n\n';

            // Check for common issues
            if (licenseSummary.includes('GPL') || licenseSummary.includes('LGPL') || licenseSummary.includes('AGPL')) {
              comment += '⚠️ **Warning:** Copyleft licenses detected (GPL/LGPL/AGPL). Please review license compatibility.\n\n';
            }

            comment += '✅ **License check completed successfully**\n\n';
          } else {
            comment += '❌ License check failed or no results generated.\n\n';
          }

          comment += '📋 **Full Report:** Available in security-reports/license-report.md';

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

    - name: Upload license reports
      uses: actions/upload-artifact@v4
      with:
        name: license-reports
        path: security-reports/license-*
        retention-days: 30
